apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:                  # <--- Das hat gefehlt!
    app: {{ .Release.Name }} # <--- Verknüpft den Service mit den Pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}